name: Publish

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-beta.[0-9]+"

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'playcanvas' }}
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24.x
          cache: "npm"
          registry-url: "https://registry.npmjs.org/"

      - name: Parse tag name
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "TAG=${TAG_NAME}" >> $GITHUB_ENV

      - name: Install Dependencies
        run: npm ci

      - name: Build PlayCanvas ESLint Config
        run: npm run build
        env:
          NODE_ENV: production

      - name: Run Publint
        run: npm run publint

      - name: Publish to npm
        run: |
          if [[ "${{ env.TAG }}" =~ "beta" ]]; then
            tag=beta
          else
            tag=latest
          fi
          npm publish --tag $tag --provenance

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          prerelease: ${{ contains(github.ref, 'alpha') || contains(github.ref, 'beta') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
