name: Publish

on:
    push:
        tags:
            - 'v[0-9]+.[0-9]+.[0-9]+'
            - 'v[0-9]+.[0-9]+.[0-9]+-beta.[0-9]+'

jobs:
    publish:
        name: Publish
        runs-on: ubuntu-latest
        if: github.repository_owner == 'playcanvas'
        steps:
            - name: Check out code
              uses: actions/checkout@v5

            - name: Set up Node.js 18.x
              uses: actions/setup-node@v6
              with:
                  node-version: 18.x
                  cache: 'npm'
                  registry-url: 'https://registry.npmjs.org/'

            - name: Parse tag name
              run: |
                  TAG_NAME=${GITHUB_REF#refs/tags/}
                  echo "TAG=${TAG_NAME}" >> $GITHUB_ENV

            - name: Install Dependencies
              run: npm ci

            - name: Build PlayCanvas ESLint Config
              run: npm run build
              env:
                  NODE_ENV: production

            - name: Run Publint
              run: npm run publint

            - name: Publish to npm
              run: |
                  if [[ "${{ env.TAG }}" =~ "beta" ]]; then
                    tag=beta
                  else
                    tag=latest
                  fi
                  npm publish --tag $tag
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
